Pharmapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('inventaire/', include('sys_inventaire.urls')),
]

core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *



app_name = 'core'

urlpatterns = [
    path('', index, name='intro'),
    path('connexion/', LoginView.as_view(), name='connexion'),
    path('deconnexion/', LogoutView.as_view(), name='deconnexion'),
    path('enregistrer/', enregistrer_user, name='enregistrement'),
]

sys_inventaire/urls.py
from django.urls import path
from .views import *

app_name = 'sys_inventaire'

urlpatterns = [
    path('', index, name='index'), 
    path('medicaments/', montrer_medicament, name='medicament'),
    path('paraphamacies/', montrer_parapharmacie, name='paraphamacies'),
    path('dietetiques/', montrer_dietetique, name='dietetiques'),
    path('pti_materiel/', montrer_petit_materiel, name='pti_materiel'), 

    # les ajouts de nouveaux produits
    path('ajoutMedicament/', ajout_medicament, name='ajouter_medicament'),
    path('ajoutpara/', ajout_parapharmacie, name='ajouter_parapharmacie'),
    path('ajoutPetitMateriel/', ajout_petit_materiel, name='ajouter_petit_materiel'),
    path('ajoutDietetique/', ajout_dietetique, name='ajouter_dietetique'),

    # La modification particuliere d'articles enregistré en cas d'erreur
    path('modifierMedicament/<int:pk>/', modifier_medicament, name='modifier_medicament'),
    path('modifierpar/<int:pk>', modifier_parapharmacie, name='modifier_parapharmacie'),
    path('modifierpetitmateriel/<int:pk>/', modifier_petit_materiel, name='modifier_petit_materiel'),
    path('modifierdietetique/<int:pk>/', modifier_dietetique, name='modifier_dietetique'),
    
    # La suppression particuliere des articles 
    path('supprimerMedicament/<int:pk>/', supprimer_medicament, name='supprimer_medicament'),
    path('supprimerParapharmatie/<int:pk>/', supprimer_parapharmatie, name='supprimer_parapharmatie'),
    path('supprimerDietetique/<int:pk>/', supprimer_dietetique, name='supprimer_dietetique'),
    path('supprimerPetitmatieriel/<int:pk>/', supprimer_petit_matériel, name='supprimer_petit_matériel')
]

sys_inventaire/models.py
from django.db import models

class Produit(models.Model):
    nom_article = models.CharField(max_length=100, blank=False)
    quantite = models.IntegerField(blank=False)
    prix = models.FloatField(blank=False)
    date_peremption = models.DateTimeField()
    Numero_lot = models.IntegerField()

    class Meta:
        abstract = True

    
    def __str__(self):
        return "nom: {0} Prix: {1} Quantité: {2}".format(self.nom_article, self.prix, self.quantite)

class Petit_matériel(Produit):
    pass 

class Parapharmatie(Produit):
    pass 

class Dietetique(Produit):
    pass 

class Article(models.Model):
    choix_groupe = (
        ('liste 1', 'Produit toxique'),
        ('Liste 2', 'Produit dangereux'),
        ('Stupéfiant', 'Stupéfiants'),
    )
    groupe = models.CharField(max_length=20, choices=choix_groupe, blank=True)
    dci = models.CharField(max_length=100, blank=True)
    specialite = models.CharField(max_length=100, blank=False)
    dose = models.CharField(max_length=100, blank=False, default='500 mg')
    quantite = models.IntegerField(blank=False)
    classe_therapeutic = models.TextField(blank=True)
    prix = models.FloatField(blank=False)
    choix_presentation = (
        ('SUPPO & OVULE', 'Suppositoire et ovule'),
        ('GOUTTE NASALE', 'Goutte nasale'),
        ('GOUTTE NASALE', 'Goutte nasale'),
        ('AMPOULE BUVABLE', 'Ampoule buvable'), 
        ('SACHET', 'Sachets'),
        ('SOLUTE', 'Solute'),
        ('COMPRIMÉ', 'Comprimé'),
        ('SIROP', 'Sirop'),
        ('POUDRE', 'Poudre'),
    )
    presentation = models.CharField(max_length=20, choices=choix_presentation, blank=True)
    date_peremption = models.DateTimeField()
    Numero_lot = models.IntegerField()

    class Meta:
        abstract = True

    def __str__(self):
        return  "Spécialité: {0} Dci: {1} prix: {2} quantité: {3}".format(
            self.specialite, self.dci, self.prix, self.quantite
        )

class Medicament(Article): 
    pass 

sys_inventaire/forms.py
from  django import forms
from .models import *

class Petit_matérielForm(forms.ModelForm):
    class Meta:
        model = Petit_matériel
        fields = ('nom_article', 'quantite', 'prix', 'date_peremption', 'Numero_lot')

class ParapharmatieForm(forms.ModelForm):
    class Meta: 
        model = Parapharmatie
        fields = ('nom_article', 'quantite', 'prix', 'date_peremption', 'Numero_lot')

class DietetiqueForm(forms.ModelForm):
    class Meta: 
        model = Dietetique
        fields = ('nom_article', 'quantite', 'prix', 'date_peremption', 'Numero_lot')

class MedicamentForm(forms.ModelForm):
    class Meta:
        model =  Medicament
        fields = ('groupe', 'dci', 'specialite', 'dose', 'quantite', 'classe_therapeutic', 'prix', 'presentation', 'date_peremption', 'Numero_lot')

sys_inventaire/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from .models import *
from .forms import *


def index(request):
    return render(request, 'inventory.html')

def montrer_medicament(request):
    items = Medicament.objects.all()
    header = 'Medicament'
    context = {
        'header':header,
        'items': items
    }
    return render(request, 'inventory.html', context)

def montrer_parapharmacie(request):
    items = Parapharmatie.objects.all()
    context = {
        'items': items,
        'titre': 'Parapharmacie'
    }
    return render(request, 'inventory.html', context)

def montrer_petit_materiel(request):
    items = Petit_matériel.objects.all()
    context = {
        'items': items,
        'titre': 'Petit matériel'
    }
    return render(request, 'inventory.html', context)

def montrer_dietetique(request):
    items = Dietetique.objects.all()
    context = {
        'items': items,
        'titre': 'Diétitique'
    }
    return render(request, 'inventory.html', context)

def ajouter_produit(request, cls):
    if request.method == 'POST':
        form = cls(request.POST)

        if form.is_valid():
            form.save()
            return redirect('sys_inventaire:index')
    else:
        form = cls()
        return render(request, 'ajout_produit.html', {'form': form})

def ajout_medicament(request):
    return ajouter_produit(request, MedicamentForm)

def ajout_petit_materiel(request):
    return ajouter_produit(request, Petit_matérielForm)

def ajout_parapharmacie(request):
    return ajouter_produit(request, ParapharmatieForm)

def ajout_dietetique(request):
    return ajouter_produit(request, DietetiqueForm)

def modifier_article(request, pk, model, cls):
    item = get_object_or_404(model, pk=pk)
    
    if request.method == 'POST':
        form = cls(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('sys_inventaire:index')
    else:
        form = cls(instance=item)
        return render(request, 'modifpage.html', {'form':form})

def modifier_medicament(request, pk):
    return modifier_article(request, pk, Medicament, MedicamentForm)


def modifier_dietetique(request, pk):
    return modifier_article(request, pk, Dietetique, DietetiqueForm)

def modifier_parapharmacie(request, pk):
    return modifier_article(request, pk, Parapharmatie, ParapharmatieForm)


def modifier_petit_materiel(request, pk):
    return modifier_article(request, pk, Petit_matériel, Petit_matérielForm)


def supprimer_medicament(request, pk):
    Medicament.objects.filter(id=pk).delete()
    items = Medicament.objects.all()
    context = {
        'items': items
    }
    return render(request, 'inventory.html', context)

def supprimer_medicament(request, pk):
    Medicament.objects.filter(id=pk).delete()
    items = Medicament.objects.all()
    context = {
        'items': items
    }
    return render(request, 'inventory.html', context)

def supprimer_parapharmatie(request, pk):
    Parapharmatie.objects.filter(id=pk).delete()
    items = Parapharmatie.objects.all()
    context = {
        'items': items
    }
    return render(request, 'inventory.html', context)

def supprimer_dietetique(request, pk):
    Dietetique.objects.filter(id=pk).delete()
    items = Dietetique.objects.all()
    context = {
        'items': items
    }
    return render(request, 'inventory.html', context)

def supprimer_petit_matériel(request, pk):
    Petit_matériel.objects.filter(id=pk).delete()
    items = Petit_matériel.objects.all()
    context = {
        'items': items
    }
    return render(request, 'inventory.html', context)

sys_inventaire/templates/ajout_produit.html
{% extends 'inventory.html' %}

{% block content %}

  <div class="container-form">
    <form method="POST">
      {% csrf_token %}

      <h4>{{ header }}</h4>

      {% for field in form %}
      <div class="form-group row">
        <label for="id_{{ field.name }}" class="col-2 col-form-label">{{ field.label }}</label>
        <div class="col-10">
          {{ field }}
        </div>
      </div>
      {% endfor %}

      <div class="form-group row">
        <div class="offset-sm-2 col-sm-6">

          <button type="submit" class="btn btn-primary">Ajouter Produit</button>

        </div>
      </div>
    </form>
  </div>


{% endblock %}

sys_inventaire/templates/inventory.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/css/style-inventaire.css' %}">
  <script src="https://kit.fontawesome.com/3f99847030.js" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Inventaire</title>
</head>
<body>
<div class="wrapper">
  <div class="sidebar">
    <h2>PHarM<span>App</span></h2>
    <ul>
      <li><a href="#"><i class="fa fa-address-card" aria-hidden="true"></i> Gestion</a></li>
      <li><a href="#"><i class="fa fa-phone-square" aria-hidden="true"></i>Contact</a></li>
      <li><a href="#"><i class="fa fa-id-badge" aria-hidden="true"></i>Profil</a></li>
      <li><a href="#"><i class="fa fa-user-circle-o" aria-hidden="true"></i>Vente</a></li>
    </ul>
    <div class="social_media">
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
  </div>
  <div class="main_content">
    {% block content %}
    <div class="header">Bienvenue !!</div>
    <div class="button-group">
  <a href="{% url 'sys_inventaire:medicament' %}" class="btn btn-primary btn-md" role="button">Medicaments</a>
  <a href="{% url 'sys_inventaire:ajouter_medicament' %}" class="btn btn-warning btn-sm" role="button"> + </a>
  <a href="{% url 'sys_inventaire:paraphamacies' %}" class="btn btn-primary btn-md" role="button">Parapharmacies</a>
  <a href="{% url 'sys_inventaire:ajouter_parapharmacie' %}" class="btn btn-warning btn-sm" role="button"> + </a>
  <a href="{% url 'sys_inventaire:pti_materiel' %}" class="btn btn-primary btn-md" role="button">Petits materiels</a>
  <a href="{% url 'sys_inventaire:ajouter_petit_materiel' %}" class="btn btn-warning btn-sm" role="button"> + </a>
  <a href="{% url 'sys_inventaire:dietetiques' %}" class="btn btn-primary btn-md" role="button">Diététiques</a>
  <a href="{% url 'sys_inventaire:ajouter_dietetique' %}" class="btn btn-warning btn-sm" role="button"> + </a>
</div><br>
{% if header %}
<center>
  <h4>Vous voyez actuellement Medicament </h4>
</center>
  
  <div class="table">
    <div class="table100 ver1 m-b-100">
        <table>
          <thead>
            <tr class="row">
                <th class="cell100 column2">#</th>
                <th class="cell100 column2">Spécialité</th>
                <th class="cell100 column3">D C I</th>
                <th class="cell100 column4">prix</th>
                <th class="cell100 column5">Quantité</th>
                <th class="cell100 column4">Options</th>
              </tr>
          </thead>
        </table>
    </div>
     
   
    
    <div class="table" >
      <div class="table100-body js-pscroll">
        <table>
          <tbody>
            {% for item in items %}
            <tr class="row">
              <td class="cell100 column2">{{ item.pk }}</td>
              <td class="cell100 column2">{{ item.specialite }}</td>
              <td class="cell100 column3">{{ item.dci }}</td>
              <td class="cell100 column4">{{ item.prix }}</td>
              <td class="cell100 column5">{{ item.quantite }}</td>
              <td>
                <a href="{% url 'sys_inventaire:modifier_medicament' item.pk %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-pencil" aria-hidden="true"></i></a>
              </td>
              <td>
                <a href="{% url 'sys_inventaire:supprimer_medicament' item.pk %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-trash" aria-hidden="true"></i></a>
              </td>
            </tr>
            {% endfor %} 
          </tbody>
        </table>
      </div>
    
    </div>
  </div> 
                         
  {% else %}
  <center>
     <h4>Vous voyez actuellement {{ titre }} </h4>
  </center>
 
  <div class="table">
    <div class="table100 ver1 m-b-100">
      <table>
        <thead>
          <tr class="row">
            <th>#</th>
            <th class="cell100 column2">Spécialité</th>
            <th class="cell100 column3">prix</th>
            <th class="cell100 column4">Quantité</th>
            <th class="cell100 column5">Date péremption</th>
            <th class="cell100 column4">Options</th>
          </tr>
        </thead>
      </table>
    </div> 
  
  <div class="table" >
    <div class="table100-body js-pscroll" >
      <table>
      <tbody>
        {% for item in items %}
        <tr class="row">
          <td class="cell100 column2">{{ item.pk }}</td>
          <td class="cell100 column2">{{ item.nom_article }}</td>
          <td class="cell100 column3">{{ item.prix }}</td>
          <td class="cell100 column4">{{ item.quantite }}</td>
          <td class="cell100 column5">{{ item.date_peremption }}</td>
          {% if titre|lower == "parapharmacie" %}
          <td>
            <a href="{% url 'sys_inventaire:modifier_parapharmacie' item.pk %}" class="btn btn-warning " role="button"><i class="fa fa-pencil" aria-hidden="true"></i></a>
          </td>
          <td>
            <a href="{% url 'sys_inventaire:supprimer_parapharmatie' item.pk %}" class="btn btn-warning " role="button"><i class="fa fa-trash" aria-hidden="true"></i></a>
          </td>
          {% elif titre|lower == "petit matériel" %}
          <td>
            <a href="{% url 'sys_inventaire:modifier_petit_materiel' item.pk %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-pencil" aria-hidden="true"></i></a>
          </td>
          <td>
            <a href="{% url 'sys_inventaire:supprimer_petit_matériel' item.pk %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-trash" aria-hidden="true"></i></a>
          </td>
          {% else %}
          <td>
            <a href="{% url 'sys_inventaire:modifier_dietetique' item.pk %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-pencil" aria-hidden="true"></i></a>
          </td>
          <td>
            <a href="{% url 'sys_inventaire:supprimer_dietetique' item.pk %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-trash" aria-hidden="true"></i></a>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>    
  </div>
</div> 

{% endif %}

  </div>
</div>
<div>
  <br>
  {% endblock %}    

</body>
</html>

sys_inventaire/templates/modifpage.html
{% extends 'inventory.html' %}

{% block content %}

  <div class="container-form">
    <form method="POST">
      {% csrf_token %}
      <center>
          <h4>Modification de l'article</h4>
      </center>
      

      <h4>{{ header }}</h4>

      {% for field in form %}
      <div class="form-group row">
        <label for="id_{{ field.name }}" class="col-2 col-form-label">{{ field.label }}</label>
        <div class="col-10">
          {{ field }}
        </div>
      </div>
      {% endfor %}

      <div class="form-group row">
        <div class="offset-sm-2 col-sm-6">

          <button type="submit" class="btn btn-primary">Ajouter Produit</button>

        </div>
      </div>
    </form>
  </div>


{% endblock %}